CREATE TABLE ALUNO(
    CONSTRAINT PK_RA PRIMARY KEY(RA,NOME),
    RA NUMBER(09),
    NOME varchar2(30),
    SEXO varchar2(01),
    RG NUMBER(12)
);



INSERT INTO(RA,NOME,SEXO,RG)
VALUES (99999,'SOUZA','F',88888);




SELECT * FROM ALUNO;